import { NextResponse } from "next/server";

import { requireAdmin } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { formatCurrency, formatDate } from "@/lib/utils";

export async function GET(_: Request, { params }: { params: Promise<{ id: string }> }) {
  await requireAdmin();
  const { id } = await params;

  const payslip = await prisma.payslip.findUnique({
    where: { id },
    include: {
      user: true,
      generatedBy: true,
      deductions: true,
    },
  });

  if (!payslip) {
    return new NextResponse("Payslip not found.", { status: 404 });
  }

  const rows = [
    ["Employee", payslip.user.name],
    ["Email", payslip.user.email],
    ["Month", payslip.monthLabel],
    ["Scheduled Working Days", String(payslip.scheduledWorkingDays)],
    ["Payable Days", String(payslip.payableDays)],
    ["Base Salary", formatCurrency(payslip.baseSalary)],
    ["Gross Earnings", formatCurrency(payslip.grossEarnings)],
    ["Total Deductions", formatCurrency(payslip.totalDeductions)],
    ["Net Pay", formatCurrency(payslip.netPay)],
    ["Generated By", payslip.generatedBy?.name ?? "Admin"],
    ["Generated On", formatDate(payslip.createdAt)],
  ];

  const deductionHtml =
    payslip.deductions.length === 0
      ? `<tr><td colspan="3" style="padding:12px;border:1px solid #e5e7eb;color:#6b7280;">No deductions applied</td></tr>`
      : payslip.deductions
          .map(
            (deduction) => `<tr>
              <td style="padding:12px;border:1px solid #e5e7eb;">${escapeHtml(deduction.label)}</td>
              <td style="padding:12px;border:1px solid #e5e7eb;">${escapeHtml(deduction.note ?? "-")}</td>
              <td style="padding:12px;border:1px solid #e5e7eb;text-align:right;">${formatCurrency(deduction.amount)}</td>
            </tr>`,
          )
          .join("");

  const infoHtml = rows
    .map(
      ([label, value]) => `<tr>
        <td style="padding:12px;border:1px solid #e5e7eb;color:#6b7280;width:240px;">${escapeHtml(label)}</td>
        <td style="padding:12px;border:1px solid #e5e7eb;font-weight:600;">${escapeHtml(value)}</td>
      </tr>`,
    )
    .join("");

  const notesHtml = payslip.notes
    ? `<div style="margin-top:24px;padding:16px;border-radius:16px;background:#f8fafc;border:1px solid #e5e7eb;">
        <p style="margin:0 0 8px 0;font-size:12px;letter-spacing:.18em;text-transform:uppercase;color:#6b7280;">Payroll Note</p>
        <p style="margin:0;font-size:14px;line-height:1.6;color:#111827;">${escapeHtml(payslip.notes)}</p>
      </div>`
    : "";

  const html = `<!DOCTYPE html>
  <html lang="en">
    <head>
      <meta charset="UTF-8" />
      <title>Taze Creative Payslip - ${escapeHtml(payslip.user.name)} - ${escapeHtml(payslip.monthLabel)}</title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    </head>
    <body style="margin:0;background:#f3f4f6;font-family:Inter,Segoe UI,Arial,sans-serif;color:#111827;">
      <div style="max-width:900px;margin:32px auto;padding:32px;background:#ffffff;border-radius:28px;box-shadow:0 24px 80px rgba(15,23,42,.08);">
        <div style="display:flex;justify-content:space-between;gap:24px;align-items:start;">
          <div>
            <p style="margin:0;font-size:12px;letter-spacing:.24em;text-transform:uppercase;color:#9ca3af;">Taze Creative</p>
            <h1 style="margin:12px 0 0 0;font-size:40px;line-height:1.1;">Monthly Payslip</h1>
            <p style="margin:12px 0 0 0;font-size:16px;color:#6b7280;">Attendance-based payroll statement for ${escapeHtml(
              payslip.monthLabel,
            )}</p>
          </div>
          <div style="padding:14px 18px;border-radius:18px;background:linear-gradient(135deg,#f97316,#fdba74);color:#fff;font-weight:700;">
            ${formatCurrency(payslip.netPay)}
          </div>
        </div>

        <div style="margin-top:28px;overflow:hidden;border-radius:20px;border:1px solid #e5e7eb;">
          <table style="width:100%;border-collapse:collapse;font-size:14px;">
            <tbody>${infoHtml}</tbody>
          </table>
        </div>

        <div style="margin-top:28px;">
          <p style="margin:0 0 12px 0;font-size:12px;letter-spacing:.18em;text-transform:uppercase;color:#6b7280;">Deductions</p>
          <div style="overflow:hidden;border-radius:20px;border:1px solid #e5e7eb;">
            <table style="width:100%;border-collapse:collapse;font-size:14px;">
              <thead style="background:#fff7ed;">
                <tr>
                  <th style="padding:12px;border:1px solid #e5e7eb;text-align:left;">Label</th>
                  <th style="padding:12px;border:1px solid #e5e7eb;text-align:left;">Note</th>
                  <th style="padding:12px;border:1px solid #e5e7eb;text-align:right;">Amount</th>
                </tr>
              </thead>
              <tbody>${deductionHtml}</tbody>
            </table>
          </div>
        </div>

        ${notesHtml}
      </div>
    </body>
  </html>`;

  const safeMonth = payslip.monthLabel.toLowerCase().replace(/\s+/g, "-");
  const safeName = payslip.user.name.toLowerCase().replace(/[^a-z0-9]+/g, "-");

  return new NextResponse(html, {
    headers: {
      "Content-Type": "text/html; charset=utf-8",
      "Content-Disposition": `attachment; filename="${safeName}-${safeMonth}-payslip.html"`,
    },
  });
}

function escapeHtml(value: string) {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}
